# Numpy Basics

In [2]:
#import numpy module
import numpy as np

In [ ]:
#create numpy array
np.array()

### Basics

- numpy array creation ~ specify the size, dtype
- numpy arrays of ones, zeroes 
- numpy.random.generator ~ generates both integers and float 
- slicing arrays
- numpy array manipulation
- numpy array mathematical and statistical operations

#### Numpy array syntax

In [18]:
# create numpy arrays from a list,tuple and specify the output data type( int or float)

#lists
cars = [[1,2,3], [4,5,6], [7,8,9]]
more_cars = [[10,11,12], [13,14,15], [16,17,18]]

#create array
car_array = np.array(cars + more_cars, dtype= float)

car_array

# np.array accepts only one list or tuple, therefore + is used to concantenate the 2 lists

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [ ]:
# arrays of zeros and ones

np.ones(size = (1,2) dtype=float)
np.zeros()


In [ ]:
# axis
axis = 0 - columns
axis = 1 - rows

#### Numpy Array Generator

In [4]:
# numpy.random.generator.integer (simple method) --- for integers
ar1 = np.random.randint(1, 6, size=(2,3))
ar1

# low=1, high =6 the array generated is exclusive of 6 i.e. array is between 1 and 5
# to include 6 we use

array([[5, 1, 2],
       [2, 1, 5]], dtype=int32)

In [5]:
#using a generator ---for integers
#create the generator
arr = np.random.default_rng()

#generate 
arr.integers(1, 6, size=(2,3) )


array([[5, 2, 1],
       [4, 4, 1]])

In [8]:
# numpy.random.generator.random for float ----simple method
# float generated is between 0 and 1

ar2 = np.random.random(size=(2,4))

ar2

array([[0.85317626, 0.82100082, 0.67505383, 0.44499141],
       [0.78429171, 0.35313953, 0.46471582, 0.60354776]])

In [9]:
# float array generator
#create generator
arra = np.random.default_rng()

#generate the float array
arra.random(size=(2,4))

array([[0.97466931, 0.78736897, 0.99019241, 0.79252543],
       [0.34841221, 0.23762025, 0.70074976, 0.56878681]])

#### slicing (indexing) arrays

syntax
np.array[vertical index, horizontal index]

#slicing a range
np.array[vertical start:stop, horizontal start:stop]


In [22]:
# generate integer array, between 1-10 and size(3,6)
slice = np.random.randint(1, 11, size=(3,6))

slice


array([[8, 5, 7, 2, 5, 1],
       [7, 9, 6, 9, 9, 6],
       [2, 6, 9, 9, 3, 8]], dtype=int32)

In [23]:
#slice row 3(index=2), the first 3 values(index=2)

slice[2, :3]

array([2, 6, 9], dtype=int32)

#boolean indexing
returns an array the meet a specic condition

#### Numpy array manipulation

np.append(array, list/tuple, axis = 0/1) - inserts an extra row or column to an existing array

np.delete(array, index , axis =0/1) - removes a row or column stated at the index

np.concatenate((array1, array2), axis =0/1 ) - joins 2 arrays at a particular axis (similar to +)

np.reshape(array, (new_shape))
        - reshape can flatten the array 

np.split(array, (parts))
    - to output a split, the variable assigned need to be equal to the split parts i.e.
    split1, split2 = np.split(array1, 2)

np.transpose()
    changes rows to columns - this commonly used to perform linear algebra in multiplication of vectors

In [27]:
#generate 2, 3 dimensional arrays
a = np.random.randint(1, 5, size=(3,3))
b = np.random.randint(5, 10, size=(3,3))

print(a)
print(b)

[[1 2 1]
 [2 2 1]
 [2 3 2]]
[[6 9 8]
 [6 6 7]
 [9 8 7]]


In [28]:
#Transposing in vector multiplication (using the dot operation)
np.dot(a, b.transpose())

array([[32, 25, 32],
       [38, 31, 41],
       [55, 44, 56]], dtype=int32)

#### Maths and Stats Numpy operations

1. Numpy mathematics

np.add(array1, array2) - adds the arrays together element wise; corresponding elements of the array ar added together

np.subtract(array1, array2)

np.divide(array1, array 2)

np.multiply(array1, array2)

np.sqrt(array)

np.power(array, power ~ eg.2,3)



In [29]:
print(a)

[[1 2 1]
 [2 2 1]
 [2 3 2]]


In [30]:
print(b)

[[6 9 8]
 [6 6 7]
 [9 8 7]]


In [32]:
#add the 2 arrays together

ad = np.add(a,b)
ad

array([[ 7, 11,  9],
       [ 8,  8,  8],
       [11, 11,  9]], dtype=int32)

In [33]:
#sum of the columns for array a
a.sum(axis=0)

array([5, 7, 4])

**
array.sum( axis= 0/1) - gives the sum of an array at the column or row level

array.min(axis= 0/1)

array.max(axis = 0/1)

np.argmax(array, axis= 0/1) index of the max number at column or row level ~ for the whole array the axis paranthesis are left blank

np.argmin(array, ) as above

#### Statistics in Numpy

np.mean(array, axis = 0/1)

np.median(array, axis = 0/1)

np.std(array, axis = 0/1)

np.variance(array, axis = 0/1)